/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosCondicionesRouteImport } from './routes/terminos-condiciones'
import { Route as RecuperarCodigoRouteImport } from './routes/recuperar-codigo'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ModoFRouteImport } from './routes/modo-f'
import { Route as ModoRouteImport } from './routes/modo'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefCodigoRouteImport } from './routes/ref.$codigo'
import { Route as DiagnosticoValidacionRouteImport } from './routes/diagnostico.validacion'
import { Route as DiagnosticoUploadRouteImport } from './routes/diagnostico.upload'
import { Route as DiagnosticoProcesandoRouteImport } from './routes/diagnostico.procesando'
import { Route as DiagnosticoPreguntasRouteImport } from './routes/diagnostico.preguntas'
import { Route as DiagnosticoPerfilRouteImport } from './routes/diagnostico.perfil'
import { Route as DiagnosticoPaywallRouteImport } from './routes/diagnostico.paywall'
import { Route as DiagnosticoInferenciaRouteImport } from './routes/diagnostico.inferencia'
import { Route as DiagnosticoConsentimientosRouteImport } from './routes/diagnostico.consentimientos'
import { Route as DiagnosticoIdRouteImport } from './routes/diagnostico.$id'
import { Route as BetaTokenRouteImport } from './routes/beta.$token'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const TerminosCondicionesRoute = TerminosCondicionesRouteImport.update({
  id: '/terminos-condiciones',
  path: '/terminos-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarCodigoRoute = RecuperarCodigoRouteImport.update({
  id: '/recuperar-codigo',
  path: '/recuperar-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoFRoute = ModoFRouteImport.update({
  id: '/modo-f',
  path: '/modo-f',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoRoute = ModoRouteImport.update({
  id: '/modo',
  path: '/modo',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodigoRoute = RefCodigoRouteImport.update({
  id: '/ref/$codigo',
  path: '/ref/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoValidacionRoute = DiagnosticoValidacionRouteImport.update({
  id: '/diagnostico/validacion',
  path: '/diagnostico/validacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoUploadRoute = DiagnosticoUploadRouteImport.update({
  id: '/diagnostico/upload',
  path: '/diagnostico/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoProcesandoRoute = DiagnosticoProcesandoRouteImport.update({
  id: '/diagnostico/procesando',
  path: '/diagnostico/procesando',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoPreguntasRoute = DiagnosticoPreguntasRouteImport.update({
  id: '/diagnostico/preguntas',
  path: '/diagnostico/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoPerfilRoute = DiagnosticoPerfilRouteImport.update({
  id: '/diagnostico/perfil',
  path: '/diagnostico/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoPaywallRoute = DiagnosticoPaywallRouteImport.update({
  id: '/diagnostico/paywall',
  path: '/diagnostico/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoInferenciaRoute = DiagnosticoInferenciaRouteImport.update({
  id: '/diagnostico/inferencia',
  path: '/diagnostico/inferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoConsentimientosRoute =
  DiagnosticoConsentimientosRouteImport.update({
    id: '/diagnostico/consentimientos',
    path: '/diagnostico/consentimientos',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticoIdRoute = DiagnosticoIdRouteImport.update({
  id: '/diagnostico/$id',
  path: '/diagnostico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaTokenRoute = BetaTokenRouteImport.update({
  id: '/beta/$token',
  path: '/beta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metodologia': typeof MetodologiaRoute
  '/modo': typeof ModoRoute
  '/modo-f': typeof ModoFRoute
  '/planes': typeof PlanesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/beta/$token': typeof BetaTokenRoute
  '/diagnostico/$id': typeof DiagnosticoIdRoute
  '/diagnostico/consentimientos': typeof DiagnosticoConsentimientosRoute
  '/diagnostico/inferencia': typeof DiagnosticoInferenciaRoute
  '/diagnostico/paywall': typeof DiagnosticoPaywallRoute
  '/diagnostico/perfil': typeof DiagnosticoPerfilRoute
  '/diagnostico/preguntas': typeof DiagnosticoPreguntasRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/upload': typeof DiagnosticoUploadRoute
  '/diagnostico/validacion': typeof DiagnosticoValidacionRoute
  '/ref/$codigo': typeof RefCodigoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metodologia': typeof MetodologiaRoute
  '/modo': typeof ModoRoute
  '/modo-f': typeof ModoFRoute
  '/planes': typeof PlanesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/beta/$token': typeof BetaTokenRoute
  '/diagnostico/$id': typeof DiagnosticoIdRoute
  '/diagnostico/consentimientos': typeof DiagnosticoConsentimientosRoute
  '/diagnostico/inferencia': typeof DiagnosticoInferenciaRoute
  '/diagnostico/paywall': typeof DiagnosticoPaywallRoute
  '/diagnostico/perfil': typeof DiagnosticoPerfilRoute
  '/diagnostico/preguntas': typeof DiagnosticoPreguntasRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/upload': typeof DiagnosticoUploadRoute
  '/diagnostico/validacion': typeof DiagnosticoValidacionRoute
  '/ref/$codigo': typeof RefCodigoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metodologia': typeof MetodologiaRoute
  '/modo': typeof ModoRoute
  '/modo-f': typeof ModoFRoute
  '/planes': typeof PlanesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-codigo': typeof RecuperarCodigoRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/beta/$token': typeof BetaTokenRoute
  '/diagnostico/$id': typeof DiagnosticoIdRoute
  '/diagnostico/consentimientos': typeof DiagnosticoConsentimientosRoute
  '/diagnostico/inferencia': typeof DiagnosticoInferenciaRoute
  '/diagnostico/paywall': typeof DiagnosticoPaywallRoute
  '/diagnostico/perfil': typeof DiagnosticoPerfilRoute
  '/diagnostico/preguntas': typeof DiagnosticoPreguntasRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/upload': typeof DiagnosticoUploadRoute
  '/diagnostico/validacion': typeof DiagnosticoValidacionRoute
  '/ref/$codigo': typeof RefCodigoRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metodologia'
    | '/modo'
    | '/modo-f'
    | '/planes'
    | '/politica-privacidad'
    | '/recuperar-codigo'
    | '/terminos-condiciones'
    | '/beta/$token'
    | '/diagnostico/$id'
    | '/diagnostico/consentimientos'
    | '/diagnostico/inferencia'
    | '/diagnostico/paywall'
    | '/diagnostico/perfil'
    | '/diagnostico/preguntas'
    | '/diagnostico/procesando'
    | '/diagnostico/upload'
    | '/diagnostico/validacion'
    | '/ref/$codigo'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metodologia'
    | '/modo'
    | '/modo-f'
    | '/planes'
    | '/politica-privacidad'
    | '/recuperar-codigo'
    | '/terminos-condiciones'
    | '/beta/$token'
    | '/diagnostico/$id'
    | '/diagnostico/consentimientos'
    | '/diagnostico/inferencia'
    | '/diagnostico/paywall'
    | '/diagnostico/perfil'
    | '/diagnostico/preguntas'
    | '/diagnostico/procesando'
    | '/diagnostico/upload'
    | '/diagnostico/validacion'
    | '/ref/$codigo'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/metodologia'
    | '/modo'
    | '/modo-f'
    | '/planes'
    | '/politica-privacidad'
    | '/recuperar-codigo'
    | '/terminos-condiciones'
    | '/beta/$token'
    | '/diagnostico/$id'
    | '/diagnostico/consentimientos'
    | '/diagnostico/inferencia'
    | '/diagnostico/paywall'
    | '/diagnostico/perfil'
    | '/diagnostico/preguntas'
    | '/diagnostico/procesando'
    | '/diagnostico/upload'
    | '/diagnostico/validacion'
    | '/ref/$codigo'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetodologiaRoute: typeof MetodologiaRoute
  ModoRoute: typeof ModoRoute
  ModoFRoute: typeof ModoFRoute
  PlanesRoute: typeof PlanesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  RecuperarCodigoRoute: typeof RecuperarCodigoRoute
  TerminosCondicionesRoute: typeof TerminosCondicionesRoute
  BetaTokenRoute: typeof BetaTokenRoute
  DiagnosticoIdRoute: typeof DiagnosticoIdRoute
  DiagnosticoConsentimientosRoute: typeof DiagnosticoConsentimientosRoute
  DiagnosticoInferenciaRoute: typeof DiagnosticoInferenciaRoute
  DiagnosticoPaywallRoute: typeof DiagnosticoPaywallRoute
  DiagnosticoPerfilRoute: typeof DiagnosticoPerfilRoute
  DiagnosticoPreguntasRoute: typeof DiagnosticoPreguntasRoute
  DiagnosticoProcesandoRoute: typeof DiagnosticoProcesandoRoute
  DiagnosticoUploadRoute: typeof DiagnosticoUploadRoute
  DiagnosticoValidacionRoute: typeof DiagnosticoValidacionRoute
  RefCodigoRoute: typeof RefCodigoRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-condiciones': {
      id: '/terminos-condiciones'
      path: '/terminos-condiciones'
      fullPath: '/terminos-condiciones'
      preLoaderRoute: typeof TerminosCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-codigo': {
      id: '/recuperar-codigo'
      path: '/recuperar-codigo'
      fullPath: '/recuperar-codigo'
      preLoaderRoute: typeof RecuperarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-f': {
      id: '/modo-f'
      path: '/modo-f'
      fullPath: '/modo-f'
      preLoaderRoute: typeof ModoFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo': {
      id: '/modo'
      path: '/modo'
      fullPath: '/modo'
      preLoaderRoute: typeof ModoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$codigo': {
      id: '/ref/$codigo'
      path: '/ref/$codigo'
      fullPath: '/ref/$codigo'
      preLoaderRoute: typeof RefCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/validacion': {
      id: '/diagnostico/validacion'
      path: '/diagnostico/validacion'
      fullPath: '/diagnostico/validacion'
      preLoaderRoute: typeof DiagnosticoValidacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/upload': {
      id: '/diagnostico/upload'
      path: '/diagnostico/upload'
      fullPath: '/diagnostico/upload'
      preLoaderRoute: typeof DiagnosticoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/procesando': {
      id: '/diagnostico/procesando'
      path: '/diagnostico/procesando'
      fullPath: '/diagnostico/procesando'
      preLoaderRoute: typeof DiagnosticoProcesandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/preguntas': {
      id: '/diagnostico/preguntas'
      path: '/diagnostico/preguntas'
      fullPath: '/diagnostico/preguntas'
      preLoaderRoute: typeof DiagnosticoPreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/perfil': {
      id: '/diagnostico/perfil'
      path: '/diagnostico/perfil'
      fullPath: '/diagnostico/perfil'
      preLoaderRoute: typeof DiagnosticoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/paywall': {
      id: '/diagnostico/paywall'
      path: '/diagnostico/paywall'
      fullPath: '/diagnostico/paywall'
      preLoaderRoute: typeof DiagnosticoPaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/inferencia': {
      id: '/diagnostico/inferencia'
      path: '/diagnostico/inferencia'
      fullPath: '/diagnostico/inferencia'
      preLoaderRoute: typeof DiagnosticoInferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/consentimientos': {
      id: '/diagnostico/consentimientos'
      path: '/diagnostico/consentimientos'
      fullPath: '/diagnostico/consentimientos'
      preLoaderRoute: typeof DiagnosticoConsentimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/$id': {
      id: '/diagnostico/$id'
      path: '/diagnostico/$id'
      fullPath: '/diagnostico/$id'
      preLoaderRoute: typeof DiagnosticoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta/$token': {
      id: '/beta/$token'
      path: '/beta/$token'
      fullPath: '/beta/$token'
      preLoaderRoute: typeof BetaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetodologiaRoute: MetodologiaRoute,
  ModoRoute: ModoRoute,
  ModoFRoute: ModoFRoute,
  PlanesRoute: PlanesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  RecuperarCodigoRoute: RecuperarCodigoRoute,
  TerminosCondicionesRoute: TerminosCondicionesRoute,
  BetaTokenRoute: BetaTokenRoute,
  DiagnosticoIdRoute: DiagnosticoIdRoute,
  DiagnosticoConsentimientosRoute: DiagnosticoConsentimientosRoute,
  DiagnosticoInferenciaRoute: DiagnosticoInferenciaRoute,
  DiagnosticoPaywallRoute: DiagnosticoPaywallRoute,
  DiagnosticoPerfilRoute: DiagnosticoPerfilRoute,
  DiagnosticoPreguntasRoute: DiagnosticoPreguntasRoute,
  DiagnosticoProcesandoRoute: DiagnosticoProcesandoRoute,
  DiagnosticoUploadRoute: DiagnosticoUploadRoute,
  DiagnosticoValidacionRoute: DiagnosticoValidacionRoute,
  RefCodigoRoute: RefCodigoRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
