
ALTER TABLE public.diagnosticos
  ADD COLUMN IF NOT EXISTS beneficio_salud_tipo text,
  ADD COLUMN IF NOT EXISTS beneficio_salud_monto numeric,
  ADD COLUMN IF NOT EXISTS bono_tipo text,
  ADD COLUMN IF NOT EXISTS bono_monto numeric,
  ADD COLUMN IF NOT EXISTS equity text,
  ADD COLUMN IF NOT EXISTS comisiones_tipo text,
  ADD COLUMN IF NOT EXISTS comisiones_monto numeric,
  ADD COLUMN IF NOT EXISTS beneficio_alimentacion_tipo text,
  ADD COLUMN IF NOT EXISTS beneficio_alimentacion_monto numeric,
  ADD COLUMN IF NOT EXISTS auto_corporativo text,
  ADD COLUMN IF NOT EXISTS beneficio_celular text,
  ADD COLUMN IF NOT EXISTS beneficio_movilidad_tipo text,
  ADD COLUMN IF NOT EXISTS beneficio_movilidad_monto numeric,
  ADD COLUMN IF NOT EXISTS beneficio_seguro_vida text,
  ADD COLUMN IF NOT EXISTS beneficio_retiro text,
  ADD COLUMN IF NOT EXISTS beneficio_401k_match text,
  ADD COLUMN IF NOT EXISTS beneficio_401k_porcentaje text,
  ADD COLUMN IF NOT EXISTS modalidad_trabajo text,
  ADD COLUMN IF NOT EXISTS modalidad_dias_presenciales text,
  ADD COLUMN IF NOT EXISTS beneficio_vacaciones_adicionales text,
  ADD COLUMN IF NOT EXISTS beneficio_capacitacion text,
  ADD COLUMN IF NOT EXISTS beneficios_no_declarados text[];
